redis_ambassdor_client:
  image: svendowideit/ambassador
  expose:
    - "6379"
  environment:
    - "REDIS_PORT_6379_TCP=tcp://52.91.202.46:6379"
redis_client:
  image: relateiq/redis-cli
  links:
    - redis_ambassdor_client:redis
